config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/person.rb
class Person < ApplicationRecord
	validates :name, presence: true
	validates :favoriteCity, presence: true

	scope :oldest, -> { order("People.created_at ASC") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :set_people

	def index
		@people = Person.all.oldest
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @people }
		end
	end

	def new 
		@people = Person.new
	end

	def create
		@people = Person.new(people_params)

		if @people.valid?
			@people.save
			redirect_to people_path
		else
			render :new
		end
	end

	def show
		respond_to do |format|
			format.html { render :show }
			format.json { render json: @people }
		end 

	end

	def edit
	
	end

	def update
		if @people.update(people_params)
        	redirect_to people_path
      	else
      		render :edit
      	end
	end

	def destroy
		@people.delete
 		redirect_to people_path
	end

	private 

	def people_params
 		params.require(:person).permit(:id, :name, :favoriteCity)
 	end

 	def set_people
		@people = Person.find_by(id: params[:id])
	end	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<% if @people.errors.any? %>
  <div id="error_explanation">
    <div class="ui warning message">
      <div class="header">
        <h2>
          <%= pluralize(@people.errors.count, "error") %>
          prohibited this person from being saved:
        </h2>
      </div>
        <ul id="warning">
          <% @people.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

<div  class="ui card" id="address_card">
  <div class="content" id="header_content">
    <h3><div class="header">Contacts 
    </div></h3>
  </div>
  <div class="content">
    <h4 class="ui sub header">
      New Contact
  </h4><br>
    <div class="ui small feed">
      <div class="event">
        <div class="content">
          <div class="ui form">
            <%= form_for @people do |f| %>
              <strong><%= f.label :name %></strong><br>
                <%= f.text_field :name %><br><br>

              <strong><%= f.label :favoriteCity, 'Favorite City' %></strong><br>
                <%= f.text_field :favoriteCity %><br><br>

                <div class="ui buttons" id="add_button">
                    <%= f.submit 'Add', class: 'ui button' %>
                  <div class="or"></div>
                    <input type="button" value="Back" class="ui positive button backButton" />
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<% if @people.errors.any? %>
  <div id="error_explanation">
    <div class="ui warning message">
      <div class="header">
        <h2>
          <%= pluralize(@people.errors.count, "error") %>
          prohibited this person from being saved:
        </h2>
      </div>
        <ul id="warning">
          <% @people.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

<div  class="ui card" id="address_card">
  <div class="content" id="header_content">
    <h3><div class="header">Contacts 
    </div></h3>
  </div>
  <div class="content">
    <h4 class="ui sub header">
      Edit Contact
  </h4><br>
    <div class="ui small feed">
      <div class="event">
        <div class="content">
          <div class="ui form">
            <%= form_for @people do |f| %>
              <strong><%= f.label :name %></strong><br>
                <%= f.text_field :name %><br><br>

              <strong><%= f.label :favoriteCity, 'Favorite City' %></strong><br>
                <%= f.text_field :favoriteCity %><br><br>

              <div class="ui buttons">
                  <%= f.submit 'Update', class: 'ui button' %>
                <div class="or"></div>
                  <input type="button" value="Back" class="ui positive button backButton"/>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/index.html.erb
<div  class="ui card" id="address_card">
  <div class="content" id="header_content">
    <h3><div class="header" >Contacts 
    </div></h3>
  </div>
  <div class="content">
    <h4 class="ui sub header">
    	<%= link_to new_person_path, :class => 'logo' do %>
    	<i class="add user icon"></i>
    		Add Contact
		<%end%>
	</h4>
    <div class="ui small feed">
      <div class="event">
        <div class="content">
          <div class="summary" id="summary">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<%= render 'form' %><br>

app/views/people/show.html.erb
<div  class="ui card" id="address_card">
  <div class="content" id="header_content">
    <h3><div class="header">Contacts 
    </div></h3>
  </div>
  <div class="content">
    <h4 class="ui sub header">
		Profile Page
	</h4></br>
    <div class="ui small feed">
      <div class="event">
        <div class="content">
          <div class="summary">
            <div class="ui buttons" id="delete_buttons">

				<%= link_to "Delete", person_path(@people), method: :delete, :class => 'ui button' %>
   
                 <div class="or"></div>

                	<input type="button" value="Back" class="ui positive button backButton" />
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="ui message" id="ui_message">
<p class="title"><strong>Contacts App</strong></p>

<p class="title">The app that allows you to keep track of a person’s/contact’s favorite city. A user can add as many contacts/people and can edit and view an individual contact’s/person’s profile.</p>

<input type="button" value="Contacts App" class="fluid ui green button appButton" />
	

<p>The user can add a new contact by clicking on <strong>Add Contact</strong> or <strong>icon</strong>. This will make a get request to <strong>/people/new</strong> and direct the user to the form used to create a new contact.</p>

<p>The user is able to enter in a contact’s name and favorite city into the appropriate fields. </p>

<p> The user is able to either add this new contact or return to the contact index <strong>/people</strong> by using the back button without adding the new contact. </p>

<p> The <strong>add button</strong> makes a post request to the create action making a new person object with the entered in values/params and the user will be redirected to the contact index page where the newest person can be viewed along with the already existing contacts. </p>

<p> The user is able to edit a contact by clicking on the <strong>edit button.</strong> This makes a get request to <strong>/people/:id/edit</strong>, which redirects the user to the form to edit this specific contact. Once the user has entered in the information, clicking the update button makes a patch request to the route <strong>/people/:id</strong> and updates the attributes and returns to the contact index page. Again the user is given the option to return to the contact index page should the user decide not to update the information. </p>

<p> Finally the user is able to delete a contact by clicking on the <strong>profile button</strong> under the contact’s information on the contact index page. This redirects the user to <strong>/people/:id</strong> where the user can either delete the contact or return to the index page should the user decide not to delete the information. </p>

<p> The <strong>delete button</strong> makes a delete request to <strong>/people/:id</strong> and deletes this person from the database. </p>


<p class="title"><strong>Contacts API</strong></p>

<p class="title">This project provides a JSON API interface view below. This is the request to the API. </p>

<p>GET /people -  This route shows a list of all the People/Contacts that the user has added</p>

<p> Returns response: </p>

<code> [{"id":1,"name":"Sean","favoriteCity":"NewYork","created_at":"2017-03-25T17:34:29.677Z","updated_at":"2017-03-25T17:34:38.425Z"},
{"id":2,"name":"Miguel","favoriteCity":"SanFrancisco","created_at":"2017-03-25T18:42:36.200Z","updated_at":"2017-03-25T18:42:36.200Z"}] </code>

<p> GET /people/:id - This route shows an individual Person/Contact </p>

<p> Returns response: </p>

<code> [{"id":1,"name":"Sean","favoriteCity":"Brooklyn","created_at":"2017-03-25T17:34:29.677Z","updated_at":"2017-03-25T17:34:38.425Z"},] </code> 

</div>